### ISSUE TITLE
models 和 config 文件夹

### ISSUE THREAD

**Issue by zhijiejia** [Fafa-DL/Awesome-Backbones#1]
models 和 config 这俩文件夹，是不是反了？

**Comment by Fafa-DL** [comment]
特意这样设置的，没问题

**Comment by joanna63** [comment]
![QQ图片20220508212655](https://user-images.githubusercontent.com/105159144/167298415-0a3b9945-8762-493a-abd4-93f1ef221290.jpg)
报错，应该怎么修改呢

**Comment by Fafa-DL** [comment]
> ![QQ图片20220508212655](https://user-images.githubusercontent.com/105159144/167298415-0a3b9945-8762-493a-abd4-93f1ef221290.jpg)
> 
> 报错，应该怎么修改呢

类别数是不是小于5，是的话在配置文件中：
方法一：topk=(1，)
方法二：直接删掉topk=(1，5)
试试！

**Comment by joanna63** [comment]
core/evaluations/accuracy.py中line9 line46的topk=(1, 5)改为topk=(1，)
core/evaluations/eval_metrics.py中line213的topk=(1, 5)改为topk=(1，)
还是报错

**Comment by joanna63** [comment]
是我理解错了，用方法一成功了，非常感谢！！
