### ISSUE TITLE
单张图像检测报错

### ISSUE THREAD

**Issue by cphsuan** [Fafa-DL/Awesome-Backbones#10]
`Loading Train_Epoch077-Loss0.423.pth
<All keys matched successfully>
Traceback (most recent call last):
  File "tools/single_test.py", line 42, in <module>
    main()
  File "tools/single_test.py", line 36, in main
    result = inference_model(model, args.img, val_pipeline, classes_names)
  File "/home/Awesome-Backbones/utils/inference.py", line 48, in inference_model
    if val_pipeline[0]['type'] != 'LoadImageFromFile':
TypeError: 'NoneType' object is not subscriptable`

运行 python tools/evaluation.py，能正常显示，测试 python tools/single_test.py 就报错了... 打印 val_pipeline，是None，想问有什么原因导致发生的呢？谢谢

**Comment by Fafa-DL** [comment]
请问是哪个模型的配置文件，方便的话粘贴下val_pipeline配置

**Comment by cphsuan** [comment]
model 是选用resnet101.py，里面没有配置val_pipeline，是配置 test_pipeline > < 改下evaluation.py里的值，就显示拉

**Comment by Fafa-DL** [comment]
是的就是这个问题，改成val_pipeline就行，我待会也会修改
------------------ 原始邮件 ------------------
发件人: cphsuan ***@***.***&gt;
发送时间: 2022年8月10日 20:55
收件人: Fafa-DL/Awesome-Backbones ***@***.***&gt;
抄送: Fafa Bro ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Fafa-DL/Awesome-Backbones] 单张图像检测报错 (Issue #10)





 
model 是选用resnet101.py，里面没有配置val_pipeline，是配置 test_pipeline &gt; < 改下evaluation.py里的值，就显示拉
