### ISSUE TITLE
evaluation 进行模型评估时，数据集从何而来

### ISSUE THREAD

**Issue by appreciatehxy** [Fafa-DL/Awesome-Backbones#101]

**Comment by Fafa-DL** [comment]
在制作数据集的时候有训练集和测试集，训练时测试集不参与更新，评估与测试集是相同的

**Comment by jackyjinjing** [comment]
> 在制作数据集的时候有训练集和测试集，训练时测试集不参与更新，评估与测试集是相同的

可以测试集和验证集分开吗，测试集由用户自己准备，验证集来源于训练集的拆分
