### ISSUE TITLE
t2t_vit_19模型主要包含哪些部分

### ISSUE THREAD

**Issue by appreciatehxy** [Fafa-DL/Awesome-Backbones#108]
我想问一下，t2t_vit_19主要使用了什么技术，主要包含哪些部分呀？类似于图片中我框出来那种
![组成部分](https://github.com/Fafa-DL/Awesome-Backbones/assets/97371550/8b611c7b-57bf-432c-8a0b-f9820a204e11)

**Comment by Fafa-DL** [comment]
这个得自己去看论文了哦~
