### ISSUE TITLE
如何提升训练效果？

### ISSUE THREAD

**Issue by MOMOANNIE** [Fafa-DL/Awesome-Backbones#109]
你好，我使用这个项目训练自己的数据，用的是乳腺超声数据做正常、良恶性的分类，其中数据集的比例是normal：133，malignant：210，benign：437，我有尝试关闭数据增强，调整batchsize以及lr的大小，现在将损失函数改成focal loss的，但推理时验证集的ACC只有90.625，这是训练的loss曲线图，可以帮我看下还能从哪些方面尝试提升性能么？
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/26375536/691a0ec0-5c95-444a-8bce-e9fc858ad2fa)
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/26375536/0ee7cc93-4562-4af4-b859-03cba29f6bee)

**Comment by Fafa-DL** [comment]
所以这就是科研啊，点数提升了文章就有了
