### ISSUE TITLE
使用感受➕一些小建议

### ISSUE THREAD

**Issue by GhYang0519** [Fafa-DL/Awesome-Backbones#11]
这个库非常棒，我在前几天使用你的库完成了一个小任务，我在resnet的基础上又增加了一个head，在这部分做了些修改（包括一些中间件），这块我看原本是只支持更换head，但是没有做对增加的支持，不知道是不是我没有仔细看，这块是否需要完善一下。还有single test部分，我看只对单一的图片做预测，这块是否需要实现对一个batch的支持，并且是否需要将val_pipeline这部分拆分出来，这样可以提前对数据进行处理。以上是我的使用感受，欢迎探讨，最终感谢你的框架。

**Comment by Fafa-DL** [comment]
hi，谢谢建议
1.在组件中新增层或更改结构确实可以不新建文件，但是教程中进行新建是为了保护原始文件（以便你随时通过修改文件名回到原始版本，通常有修改最好是先进行备份），也就意味着如果不想新建新模块加入到__init__.py，也可以在原始文件中进行更改，但不建议这么做。如果你完全定义了一个新的head，那建议新建文件并将这个模块添加至__init__.py进行注册，如教程所示；
2.已经不止一个建议加批量检测，接下来会做这个事，视频检测已经实现；
3.批量检测是需要先进行图片预处理，会不断完善这个仓库，再次感谢，欢迎推广，随时issue。

**Comment by GhYang0519** [comment]
> hi，谢谢建议 1.在组件中新增层或更改结构确实可以不新建文件，但是教程中进行新建是为了保护原始文件（以便你随时通过修改文件名回到原始版本，通常有修改最好是先进行备份），也就意味着如果不想新建新模块加入到__init__.py，也可以在原始文件中进行更改，但不建议这么做。如果你完全定义了一个新的head，那建议新建文件并将这个模块添加至__init__.py进行注册，如教程所示； 2.已经不止一个建议加批量检测，接下来会做这个事，视频检测已经实现； 3.批量检测是需要先进行图片预处理，会不断完善这个仓库，再次感谢，欢迎推广，随时issue。

感谢回复～ 
1.我那个新加head的意思是 就是有两个head= =，这块我不知道需不需要支持一下，更换head这个我了解了。
2.看到了最近的更新 ～
3.再次向大佬致敬，🫡，真的很棒，这个库既照顾到了初学者，同时也有很好的扩展性和实用性！

**Comment by Fafa-DL** [comment]
> > hi，谢谢建议 1.在组件中新增层或更改结构确实可以不新建文件，但是教程中进行新建是为了保护原始文件（以便你随时通过修改文件名回到原始版本，通常有修改最好是先进行备份），也就意味着如果不想新建新模块加入到__init__.py，也可以在原始文件中进行更改，但不建议这么做。如果你完全定义了一个新的head，那建议新建文件并将这个模块添加至__init__.py进行注册，如教程所示； 2.已经不止一个建议加批量检测，接下来会做这个事，视频检测已经实现； 3.批量检测是需要先进行图片预处理，会不断完善这个仓库，再次感谢，欢迎推广，随时issue。
> 
> 
> 
> 感谢回复～ 
> 
> 1.我那个新加head的意思是 就是有两个head= =，这块我不知道需不需要支持一下，更换head这个我了解了。
> 
> 2.看到了最近的更新 ～
> 
> 3.再次向大佬致敬，🫡，真的很棒，这个库既照顾到了初学者，同时也有很好的扩展性和实用性！

不好意思没看到，两个head是指你有多个输出头吗？这样的话loss什么的应该都需要改动。

**Comment by GhYang0519** [comment]
> > > hi，谢谢建议 1.在组件中新增层或更改结构确实可以不新建文件，但是教程中进行新建是为了保护原始文件（以便你随时通过修改文件名回到原始版本，通常有修改最好是先进行备份），也就意味着如果不想新建新模块加入到__init__.py，也可以在原始文件中进行更改，但不建议这么做。如果你完全定义了一个新的head，那建议新建文件并将这个模块添加至__init__.py进行注册，如教程所示； 2.已经不止一个建议加批量检测，接下来会做这个事，视频检测已经实现； 3.批量检测是需要先进行图片预处理，会不断完善这个仓库，再次感谢，欢迎推广，随时issue。
> > 
> > 
> > 感谢回复～
> > 1.我那个新加head的意思是 就是有两个head= =，这块我不知道需不需要支持一下，更换head这个我了解了。
> > 2.看到了最近的更新 ～
> > 3.再次向大佬致敬，🫡，真的很棒，这个库既照顾到了初学者，同时也有很好的扩展性和实用性！
> 
> 不好意思没看到，两个head是指你有多个输出头吗？这样的话loss什么的应该都需要改动。

是的 已经都改好了 但是我不知道有没有对所有模型都兼容这个特性的必要～  比如 在一些模型中 我不单单想改模型的一些组件的参数，有时候可能在尝试的过程中我可能会加入其他模态的信息(比如文本) 或者对于不同的任务我可能有多个head 等等... 对于类似这方面的需求 我觉得可能还需要做一些扩展 。
总的来说就是 我想降低我修改模型结构的成本，比如我新看了一个算法，作者开放了他的仓库，我想要在我数据集跑起来，最快的方法就是拉他的代码，稍微修改一下配置文件，直接就可以跑起来，但是往往有些时候，模型的场景或者效果和我的情况不吻合，那这个时候我想要做一些修改，这个成本是比较大的，我需要先读懂作者的代码，再在基础上做一些修改。可能我这个想法并不好实现。。只是有这个想法，最近也在看mmcv等等一些相关的框架代码，想弄一个方便自己用的框架。

**Comment by Fafa-DL** [comment]
> > > > hi，谢谢建议 1.在组件中新增层或更改结构确实可以不新建文件，但是教程中进行新建是为了保护原始文件（以便你随时通过修改文件名回到原始版本，通常有修改最好是先进行备份），也就意味着如果不想新建新模块加入到__init__.py，也可以在原始文件中进行更改，但不建议这么做。如果你完全定义了一个新的head，那建议新建文件并将这个模块添加至__init__.py进行注册，如教程所示； 2.已经不止一个建议加批量检测，接下来会做这个事，视频检测已经实现； 3.批量检测是需要先进行图片预处理，会不断完善这个仓库，再次感谢，欢迎推广，随时issue。
> 
> > > 
> 
> > > 
> 
> > > 感谢回复～
> 
> > > 1.我那个新加head的意思是 就是有两个head= =，这块我不知道需不需要支持一下，更换head这个我了解了。
> 
> > > 2.看到了最近的更新 ～
> 
> > > 3.再次向大佬致敬，🫡，真的很棒，这个库既照顾到了初学者，同时也有很好的扩展性和实用性！
> 
> > 
> 
> > 不好意思没看到，两个head是指你有多个输出头吗？这样的话loss什么的应该都需要改动。
> 
> 
> 
> 是的 已经都改好了 但是我不知道有没有对所有模型都兼容这个特性的必要～  比如 在一些模型中 我不单单想改模型的一些组件的参数，有时候可能在尝试的过程中我可能会加入其他模态的信息(比如文本) 或者对于不同的任务我可能有多个head 等等... 对于类似这方面的需求 我觉得可能还需要做一些扩展 。
> 
> 总的来说就是 我想降低我修改模型结构的成本，比如我新看了一个算法，作者开放了他的仓库，我想要在我数据集跑起来，最快的方法就是拉他的代码，稍微修改一下配置文件，直接就可以跑起来，但是往往有些时候，模型的场景或者效果和我的情况不吻合，那这个时候我想要做一些修改，这个成本是比较大的，我需要先读懂作者的代码，再在基础上做一些修改。可能我这个想法并不好实现。。只是有这个想法，最近也在看mmcv等等一些相关的框架代码，想弄一个方便自己用的框架。

是这样的，因为所有人发布仓库有自己的编码风格，没有统一的标准，所以必须读懂其代码才能集成。如果为了发论文啥的可以选择集成几个要对比的模型。

**Comment by GhYang0519** [comment]
> > > > > hi，谢谢建议 1.在组件中新增层或更改结构确实可以不新建文件，但是教程中进行新建是为了保护原始文件（以便你随时通过修改文件名回到原始版本，通常有修改最好是先进行备份），也就意味着如果不想新建新模块加入到__init__.py，也可以在原始文件中进行更改，但不建议这么做。如果你完全定义了一个新的head，那建议新建文件并将这个模块添加至__init__.py进行注册，如教程所示； 2.已经不止一个建议加批量检测，接下来会做这个事，视频检测已经实现； 3.批量检测是需要先进行图片预处理，会不断完善这个仓库，再次感谢，欢迎推广，随时issue。
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 感谢回复～
> > 
> > 
> > > > 1.我那个新加head的意思是 就是有两个head= =，这块我不知道需不需要支持一下，更换head这个我了解了。
> > 
> > 
> > > > 2.看到了最近的更新 ～
> > 
> > 
> > > > 3.再次向大佬致敬，🫡，真的很棒，这个库既照顾到了初学者，同时也有很好的扩展性和实用性！
> > 
> > 
> > > 
> > 
> > 
> > > 不好意思没看到，两个head是指你有多个输出头吗？这样的话loss什么的应该都需要改动。
> > 
> > 
> > 是的 已经都改好了 但是我不知道有没有对所有模型都兼容这个特性的必要～  比如 在一些模型中 我不单单想改模型的一些组件的参数，有时候可能在尝试的过程中我可能会加入其他模态的信息(比如文本) 或者对于不同的任务我可能有多个head 等等... 对于类似这方面的需求 我觉得可能还需要做一些扩展 。
> > 总的来说就是 我想降低我修改模型结构的成本，比如我新看了一个算法，作者开放了他的仓库，我想要在我数据集跑起来，最快的方法就是拉他的代码，稍微修改一下配置文件，直接就可以跑起来，但是往往有些时候，模型的场景或者效果和我的情况不吻合，那这个时候我想要做一些修改，这个成本是比较大的，我需要先读懂作者的代码，再在基础上做一些修改。可能我这个想法并不好实现。。只是有这个想法，最近也在看mmcv等等一些相关的框架代码，想弄一个方便自己用的框架。
> 
> 是这样的，因为所有人发布仓库有自己的编码风格，没有统一的标准，所以必须读懂其代码才能集成。如果为了发论文啥的可以选择集成几个要对比的模型。

嗯嗯，是的，不是为了发论文。。 = =，只是自己工作起来用着方便，我再思考思考，主要还是想在懂得原理的基础上能快速的将模型应用在自己的任务中。

**Comment by GhYang0519** [comment]
感谢回复～🙏

**Comment by Fafa-DL** [comment]
> 感谢回复～🙏
> 
> 

欢迎提交merge共同维护仓库，成为contributor对未来应聘也会有帮助
