### ISSUE TITLE
批量测试报错

### ISSUE THREAD

**Issue by Livesoso** [Fafa-DL/Awesome-Backbones#117]
您好，我批量测试的时候就会出问题，tools/evaluation.py时没问题，请看我的截图
![屏幕截图 2024-07-24 094948](https://github.com/user-attachments/assets/62fe3afc-e17d-4140-b8e9-97bca64a13ab)
![屏幕截图 2024-07-24 094948](https://github.com/user-attachments/assets/77ea8686-7aa8-41f6-b207-3407272cb689)

**Comment by jackyjinjing** [comment]
可以把你的命令贴一下吗
