### ISSUE TITLE
how to change to the 2 classes classification?

### ISSUE THREAD

**Issue by qym77** [Fafa-DL/Awesome-Backbones#119]
where and how to change the code? how can i learn the structure better,now i just can run the code but don't know how to change it to fit my need.

**Comment by Fafa-DL** [comment]
Please check tutorials, which should answer your questions.

**Comment by qym77** [comment]
> Please check tutorials, which should answer your questions.

yes，sorry to ask this stupid question，the tutorials is so great! and i'd like to know how to write such beautiful and elegant code，because i think my code ability is always so poor and find no way to improve

**Comment by qym77** [comment]
> Please check tutorials, which should answer your questions.

thank you very much for your work！
