### ISSUE TITLE
请问模型图片输入大小如何修改

### ISSUE THREAD

**Issue by jang1998** [Fafa-DL/Awesome-Backbones#12]
作者您好，最近在使用您的这个项目在测试实验，请问如何在哪里可以修改输入图片大小，我的图片是自制的比如3*9、18*9。模型的默认输入是224*224。直接调用也没问题，但是好像是resize图片把图片变成了224*224，我想使用原本图片的大小作为输入

**Comment by Fafa-DL** [comment]
可以自己给图像加自适应边框，比如在周围填充像素，目标检测中很多这样做，比如早期yolov3。如果有需要我可以放在tools中。

**Comment by lmqhello** [comment]
这个应该跟网络模型也有关系，卷积提取特征的时候，参数是有影响的，所以不同尺寸在进入模型之前都会被resize成统一尺寸吧。

**Comment by Fafa-DL** [comment]
> 这个应该跟网络模型也有关系，卷积提取特征的时候，参数是有影响的，所以不同尺寸在进入模型之前都会被resize成统一尺寸吧。

修改input层就行，卷积只会维护其卷积核大小的权重，无差别对待不同size的feature map
