### ISSUE TITLE
RepVGG的结构转换

### ISSUE THREAD

**Issue by hefan14** [Fafa-DL/Awesome-Backbones#121]
您好，我尝试用RepVGG模型做二分类任务，但在测试推理阶段没有达到预期的速度。RepVGG论文中表示在训练时采用多分支结构，推理时则转换为单分支的简化结构，请问我需要自己添加结构转换部分的代码吗？还是源文件中已经包含但被我忽略了？

**Comment by Fafa-DL** [comment]
具体的训练策略可能需要自己处理，这里更多体现在结构的实现
