### ISSUE TITLE
为啥evaluation脚本的pipeline用的是trainPipeline，而不是valPipeline

### ISSUE THREAD

**Issue by jackyjinjing** [Fafa-DL/Awesome-Backbones#122]
![image](https://github.com/user-attachments/assets/1788e971-5d3f-425a-8b7d-82e2a92b86c1)

**Comment by jackyjinjing** [comment]
![image](https://github.com/user-attachments/assets/d671b7d1-3a06-4e52-b5bd-191e4fd18ecf)

**Comment by Fafa-DL** [comment]
看起来确实不合理，找时间修改再推送，感谢你的工作

**Comment by Fafa-DL** [comment]
已修复
