### ISSUE TITLE
您好，请问resnet18的结构是pytorch官方的吗？我将您的权重及用自己数据集微调的权重作为其他网络的backbone，提示以下内容

### ISSUE THREAD

**Issue by luobendewugong** [Fafa-DL/Awesome-Backbones#123]
<img width="852" alt="提示" src="https://github.com/user-attachments/assets/2e421070-d348-4e79-8f71-e49444d55be1">

您好，非常感谢您的工作，但在使用过程中遇到如题目的问题，希望向您咨询。谢谢！

**Comment by Fafa-DL** [comment]
谢谢支持，你需要搞清楚权重结构就是字典格式，权重映射则是将匹配上的key（layer名）赋上权重信息，所以你需要确保key命名一致
