### ISSUE TITLE
请问运行EfficientFormer时这个报错怎么解决呀 Can't get attribute 'OrderedDict' on <module 'typing' from 'D:\\anaconda\\envs\\aone\\lib\\typing.py'>

### ISSUE THREAD

**Issue by xinsuileya** [Fafa-DL/Awesome-Backbones#126]

**Comment by xinsuileya** [comment]
具体的报错信息是:
Traceback (most recent call last):
  File "tools/train.py", line 170, in <module>
    main()
  File "tools/train.py", line 153, in main
    model = init_model(model, data_cfg, device=device, mode='train')
  File "C:\Users\1\Desktop\Awesome-Backbones-main\Awesome-Backbones-main\utils\inference.py", line 21, in init_model
    load_checkpoint(model,data_cfg.get('train').get('pretrained_weights'),device,False)
  File "C:\Users\1\Desktop\Awesome-Backbones-main\Awesome-Backbones-main\utils\checkpoint.py", line 217, in load_checkpoint
    checkpoint = torch.load(filename, map_location)
  File "D:\anaconda\envs\aone\lib\site-packages\torch\serialization.py", line 595, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda\envs\aone\lib\site-packages\torch\serialization.py", line 854, in _load
    result = unpickler.load()
AttributeError: Can't get attribute 'OrderedDict' on <module 'typing' from 'D:\\anaconda\\envs\\aone\\lib\\typing.py'>

**Comment by Fafa-DL** [comment]
torch什么版本？看起来是torch不兼容

**Comment by xinsuileya** [comment]
> torch什么版本？看起来是torch不兼容

torch是1.7.1的版本

**Comment by Fafa-DL** [comment]
这个错误信息表明在尝试加载一个PyTorch模型的检查点（checkpoint）时出现了问题。错误的根本原因是在反序列化过程中，`torch.load` 无法找到一个名为 `OrderedDict` 的属性，它期望这个属性在 `typing` 模块中，但是它在错误的路径下查找了这个模块。

这个问题通常发生在使用不同版本的PyTorch时，尤其是当保存检查点的PyTorch版本和加载检查点的PyTorch版本不兼容时。`OrderedDict` 在较新版本的PyTorch中已经从 `torch.nn` 模块移到了 `typing` 模块。

要解决这个问题，你可以尝试以下几种方法：

1. **确保PyTorch版本一致**：确保你用来加载检查点的PyTorch版本与用来保存检查点的版本一致。如果不一致，请升级或降级你的PyTorch到相应的版本。

2. **手动修复**：如果你无法更改PyTorch版本，你可以尝试在加载检查点之前，手动将 `OrderedDict` 导入到 `typing` 模块中。这种方法并不推荐，因为它可能引入其他问题。

   ```python
   import torch
   import typing
   from torch.nn import OrderedDict

   # 将OrderedDict添加到typing模块中
   setattr(typing, 'OrderedDict', OrderedDict)

   # 现在尝试加载检查点
   checkpoint = torch.load(filename, map_location=device)
   ```

3. **使用`torch.load`的`allow_pickle`参数**：确保在调用 `torch.load` 时使用 `allow_pickle=True` 参数，因为默认情况下，从PyTorch 1.5开始，这个参数被设置为 `True`。

   ```python
   checkpoint = torch.load(filename, map_location=device, allow_pickle=True)
   ```

4. **检查环境**：确保你没有在不同的环境中安装了不同版本的PyTorch，这可能会导致模块路径混乱。

5. **使用`torch.jit.load`**：如果你的检查点是用 `torch.jit.save` 保存的，尝试使用 `torch.jit.load` 来加载模型。

   ```python
   model = torch.jit.load(filename, map_location=device)
   ```

6. **检查`typing`模块的路径**：确保`typing`模块的路径是正确的，没有被错误地重写或覆盖。

如果上述方法都无法解决问题，你可能需要检查你的代码和环境设置，或者考虑在PyTorch社区寻求帮助。

**Comment by xinsuileya** [comment]
> 这个错误信息表明在尝试加载一个PyTorch模型的检查点（checkpoint）时出现了问题。错误的根本原因是在反序列化过程中，`torch.load` 无法找到一个名为 `OrderedDict` 的属性，它期望这个属性在 `typing` 模块中，但是它在错误的路径下查找了这个模块。
> 
> 这个问题通常发生在使用不同版本的PyTorch时，尤其是当保存检查点的PyTorch版本和加载检查点的PyTorch版本不兼容时。`OrderedDict` 在较新版本的PyTorch中已经从 `torch.nn` 模块移到了 `typing` 模块。
> 
> 要解决这个问题，你可以尝试以下几种方法：
> 
> 1. **确保PyTorch版本一致**：确保你用来加载检查点的PyTorch版本与用来保存检查点的版本一致。如果不一致，请升级或降级你的PyTorch到相应的版本。
> 2. **手动修复**：如果你无法更改PyTorch版本，你可以尝试在加载检查点之前，手动将 `OrderedDict` 导入到 `typing` 模块中。这种方法并不推荐，因为它可能引入其他问题。
>    ```python
>    import torch
>    import typing
>    from torch.nn import OrderedDict
>    
>    # 将OrderedDict添加到typing模块中
>    setattr(typing, 'OrderedDict', OrderedDict)
>    
>    # 现在尝试加载检查点
>    checkpoint = torch.load(filename, map_location=device)
>    ```
> 3. **使用`torch.load`的`allow_pickle`参数**：确保在调用 `torch.load` 时使用 `allow_pickle=True` 参数，因为默认情况下，从PyTorch 1.5开始，这个参数被设置为 `True`。
>    ```python
>    checkpoint = torch.load(filename, map_location=device, allow_pickle=True)
>    ```
> 4. **检查环境**：确保你没有在不同的环境中安装了不同版本的PyTorch，这可能会导致模块路径混乱。
> 5. **使用`torch.jit.load`**：如果你的检查点是用 `torch.jit.save` 保存的，尝试使用 `torch.jit.load` 来加载模型。
>    ```python
>    model = torch.jit.load(filename, map_location=device)
>    ```
> 6. **检查`typing`模块的路径**：确保`typing`模块的路径是正确的，没有被错误地重写或覆盖。
> 
> 如果上述方法都无法解决问题，你可能需要检查你的代码和环境设置，或者考虑在PyTorch社区寻求帮助。

好的，感谢感谢，我试试。
