### ISSUE TITLE
split_data工具感觉没有必要实际复制图片

### ISSUE THREAD

**Issue by jackyjinjing** [Fafa-DL/Awesome-Backbones#129]
如题，如果复制训新的数据时，图片数量较多的情况下，复制图片就要很久时间；另外split_data只是拆分数据即可，train.txt类似的文件里面直接保存原始图片地址，这样可以节省很多时间和空间，up主觉得列

**Comment by Fafa-DL** [comment]
在很多项目下数据处理的思路大都是拷贝一份出来单独处理，**对原始数据起到保护作用**。**避免因多人协作/环境共用（如实验室工作站）时出现数据误操作问题**，当然如果这个只有你自己在用且存储资源吃紧的情况下可以如题所述那样处理，但我个人还是不建议这种不规范的操作
