### ISSUE TITLE
在单机多显卡环境下，中断训练后resume报错，

### ISSUE THREAD

**Issue by sunshare10** [Fafa-DL/Awesome-Backbones#13]
Traceback (most recent call last):
  File "tools/train1.py", line 178, in <module>
    main()
  File "tools/train1.py", line 172, in main
    train(model,runner, lr_update_func, device, epoch, data_cfg.get('train').get('epoches'), meta)
  File "/hy-tmp/Awe/utils/train_utils.py", line 215, in train
    losses = model(images,targets=targets,return_loss=True)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hy-tmp/Awe/models/build.py", line 125, in forward
    return self.forward_train(x,**kwargs)
  File "/hy-tmp/Awe/models/build.py", line 130, in forward_train
    x = self.extract_feat(x)
  File "/hy-tmp/Awe/models/build.py", line 113, in extract_feat
    x = self.backbone(img)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hy-tmp/Awe/configs/backbones/swin_transformer.py", line 409, in forward
    x, hw_shape = self.patch_embed(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/hy-tmp/Awe/configs/common/transformer.py", line 221, in forward
    x = self.projection(x)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py", line 419, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

在
![图片](https://user-images.githubusercontent.com/49760673/187864216-f51f422a-d75f-433b-8715-a29a651fb464.png)
加model.to(device),后报另一个错误
![图片](https://user-images.githubusercontent.com/49760673/187864369-297e3542-6c37-44e5-8916-436b6baa6022.png)

**Comment by Fafa-DL** [comment]
看报错是因为前后训练cuda id不匹配，因为目前没对多卡进行支持，默认在cuda0上训练，应该需要你指定某块gpu。

**Comment by sunshare10** [comment]
训练时指定cuda id可以进行训练，但在恢复训练时出错

**Comment by sunshare10** [comment]
> 看报错是因为前后训练cuda id不匹配，因为目前没对多卡进行支持，默认在cuda0上训练，应该需要你指定某块gpu。

训练时指定cuda id可以进行训练，但在恢复训练时出错

**Comment by Fafa-DL** [comment]
> > 看报错是因为前后训练cuda id不匹配，因为目前没对多卡进行支持，默认在cuda0上训练，应该需要你指定某块gpu。
> 
> 
> 
> 训练时指定cuda id可以进行训练，但在恢复训练时出错

试试在utils/train_utils.py中，147行将
device_id = torch.cuda.current_device()
改成你之前训练时的gpu号，如device_id = 1。
因为我没多卡，无法调试，期待进一步反馈。

**Comment by sunshare10** [comment]
> > > 看报错是因为前后训练cuda id不匹配，因为目前没对多卡进行支持，默认在cuda0上训练，应该需要你指定某块gpu。
> > 
> > 
> > 训练时指定cuda id可以进行训练，但在恢复训练时出错
> 
> 试试在utils/train_utils.py中，147行将 device_id = torch.cuda.current_device() 改成你之前训练时的gpu号，如device_id = 1。 因为我没多卡，无法调试，期待进一步反馈。

![图片](https://user-images.githubusercontent.com/49760673/188883470-fe0270ae-3d56-4d9a-880d-cab9c192e94d.png)
修改device_id还是报错

**Comment by sunshare10** [comment]
> > > 看报错是因为前后训练cuda id不匹配，因为目前没对多卡进行支持，默认在cuda0上训练，应该需要你指定某块gpu。
> > 
> > 
> > 训练时指定cuda id可以进行训练，但在恢复训练时出错
> 
> 试试在utils/train_utils.py中，147行将 device_id = torch.cuda.current_device() 改成你之前训练时的gpu号，如device_id = 1。 因为我没多卡，无法调试，期待进一步反馈。

gpu的调用没问题，关键是有什么东西在cpu上，是optimizer吗 ？

**Comment by sunshare10** [comment]
> > > 看报错是因为前后训练cuda id不匹配，因为目前没对多卡进行支持，默认在cuda0上训练，应该需要你指定某块gpu。
> > 
> > 
> > 训练时指定cuda id可以进行训练，但在恢复训练时出错
> 
> 试试在utils/train_utils.py中，147行将 device_id = torch.cuda.current_device() 改成你之前训练时的gpu号，如device_id = 1。 因为我没多卡，无法调试，期待进一步反馈。

在多卡环境下要禁用
    if device != torch.device('cpu'):
        model = DataParallel(model,device_ids=[args.gpu_id])
但在恢复训练时需要重新使用这一命令，且指定好gpu_id
同时有可能报cuda内存不足的问题，在前面加
CUDA_VISIBLE_DEVICES=1 python tools/train.py models/swin_transformer/base_280.py --resume-from=/hy-tmp/logs/SwinTransformer/2022-09-07-00-42-35/Last_Epoch056.pth即可

**Comment by Fafa-DL** [comment]
> > > > 看报错是因为前后训练cuda id不匹配，因为目前没对多卡进行支持，默认在cuda0上训练，应该需要你指定某块gpu。
> > > 
> > > 
> > > 训练时指定cuda id可以进行训练，但在恢复训练时出错
> > 
> > 
> > 试试在utils/train_utils.py中，147行将 device_id = torch.cuda.current_device() 改成你之前训练时的gpu号，如device_id = 1。 因为我没多卡，无法调试，期待进一步反馈。
> 
> 在多卡环境下要禁用 if device != torch.device('cpu'): model = DataParallel(model,device_ids=[args.gpu_id]) 但在恢复训练时需要重新使用这一命令，且指定好gpu_id 同时有可能报cuda内存不足的问题，在前面加 CUDA_VISIBLE_DEVICES=1 python tools/train.py models/swin_transformer/base_280.py --resume-from=/hy-tmp/logs/SwinTransformer/2022-09-07-00-42-35/Last_Epoch056.pth即可

model = DataParallel(model,device_ids=[args.gpu_id]) 改为---->model = DataParallel(model.cuda(),device_ids=[args.gpu_id])
