### ISSUE TITLE
功能建议：输出feature.npy

### ISSUE THREAD

**Issue by 63110w0r1d** [Fafa-DL/Awesome-Backbones#15]
可以增加输出backbone提取的feature的功能，并保存npy文件到指定文件夹。这样可以方便做分类降维可视化。还有就是可以提供打印网络结构的功能，最后再次谢谢大佬提供的框架！

**Comment by Fafa-DL** [comment]
好的谢谢建议，也欢迎merge成为contributor共同维护~

**Comment by 63110w0r1d** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by lmqhello** [comment]
支持

**Comment by zxy1022** [comment]
请问该功能实现了嘛，如何使用tsne降维可视化呢

**Comment by 63110w0r1d** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 63110w0r1d** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
