### ISSUE TITLE
请问一下，有什么方法可以查看模型的计算量flops吗

### ISSUE THREAD

**Issue by sunshare10** [Fafa-DL/Awesome-Backbones#16]
请问一下，有什么方法可以查看模型的计算量flops吗

**Comment by Fafa-DL** [comment]
这个其实我看很多都是测试阶段，还有点复杂，后面有时间会复现过来

**Comment by sunshare10** [comment]
嗯嗯，我去swin transformer的官方代码里面找到了，谢谢

**Comment by Fafa-DL** [comment]
> 请问一下，有什么方法可以查看模型的计算量flops吗

已经集成啦，一直忘回复了，很久前集成了flops与params计算的功能
