### ISSUE TITLE
功能完善建议

### ISSUE THREAD

**Issue by njzyxiong** [Fafa-DL/Awesome-Backbones#2]
1）可以考虑把每个epoch训练的loss，精度，验证的精度和loss等相关信息存放在一个CSV文件中，这样可以方便之后画图
2）可以考虑把每次训练的控制台输出同时添加到某个日志文件中
只是友善的建议，博主可以视情况采纳

**Comment by Fafa-DL** [comment]
收到，正在做这个事，谢谢建议。

**Comment by Fafa-DL** [comment]
已更新各训练周期评价指标保存、Loss-Acc曲线图

**Comment by njzyxiong** [comment]
> 已更新各训练周期评价指标保存、Loss-Acc曲线图

博主神速，点赞

**Comment by njzyxiong** [comment]
博主，请问一下，能否添加在训练过程中，验证的loss信息和训练的精度信息

**Comment by Fafa-DL** [comment]
> 博主，请问一下，能否添加在训练过程中，验证的loss信息和训练的精度信息

有这个需求吗，我看很多都没在训练时记录验证结果

**Comment by zhigangjun** [comment]
> > 博主，请问一下，能否添加在训练过程中，验证的loss信息和训练的精度信息
> 
> 有这个需求吗，我看很多都没在训练时记录验证结果

博主，有做用C++调用这个项目训练出来的模型吗，我在做torch.jit.trace(model, example)转化模型时会报错，显示build.py中forward_train(self,x,targets,**kwargs)缺少输入，您知道怎么解决不？
Loading Train_Epoch042-Loss0.012.pth
<All keys matched successfully>
Traceback (most recent call last):
  File "tools/pth2pt.py", line 125, in <module>
    main()
  File "tools/pth2pt.py", line 121, in main
    traced_script_module = torch.jit.trace(model, example)
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\jit\_trace.py", line 742, in trace
    _module_class,
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\jit\_trace.py", line 940, in trace_module
    _force_outplace,
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "E:\python\Awesome-Backbones\models\build.py", line 125, in forward
    return self.forward_train(x,**kwargs)
TypeError: forward_train() missing 1 required positional argument: 'targets'

**Comment by liangsiping2019** [comment]
> > > 博主，请问一下，能否添加在训练过程中，验证的loss信息和训练的精度信息
> > 
> > 
> > 有这个需求吗，我看很多都没在训练时记录验证结果
> 
> 博主，有做用C++调用这个项目训练出来的模型吗，我在做torch.jit.trace(model, example)转化模型时会报错，显示build.py中forward_train(self,x,targets,**kwargs)缺少输入，您知道怎么解决不？ Loading Train_Epoch042-Loss0.012.pth Traceback (most recent call last): File "tools/pth2pt.py", line 125, in main() File "tools/pth2pt.py", line 121, in main traced_script_module = torch.jit.trace(model, example) File "D:\anaconda3\envs\torch\lib\site-packages\torch\jit_trace.py", line 742, in trace _module_class, File "D:\anaconda3\envs\torch\lib\site-packages\torch\jit_trace.py", line 940, in trace_module _force_outplace, File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 725, in _call_impl result = self._slow_forward(*input, **kwargs) File "D:\anaconda3\envs\torch\lib\site-packages\torch\nn\modules\module.py", line 709, in _slow_forward result = self.forward(*input, **kwargs) File "E:\python\Awesome-Backbones\models\build.py", line 125, in forward return self.forward_train(x,**kwargs) TypeError: forward_train() missing 1 required positional argument: 'targets'

转onnx遇到一样的问题，说是代码里面保存的是权重，没有模型的网络结构，但是改了之后还是会有问题

**Comment by Fafa-DL** [comment]
train 与val相关metrics与loss均支持保存了~
