### ISSUE TITLE
module utils.train_utils not available for import get_info

### ISSUE THREAD

**Issue by 1doshi** [Fafa-DL/Awesome-Backbones#21]
maybe it update the title? i cant find and install that module. My mistake "from utils.train_utils import get_info ModuleNotFoundError: No module named 'utils.train_utils'"

**Comment by 1doshi** [comment]
error arise in "get_annotation.py". I follow the tutorial for testing models (https://blog.csdn.net/zzh516451964zzh/article/details/124596425) and on 1.3 point cant go next.

**Comment by Fafa-DL** [comment]
As mentioned in the second step of 1.3, please open the terminal in the `Awesome-Backbones/` directory to run

**Comment by 1doshi** [comment]
currently i got that:
  File "Awesome-Backbones\tools\get_annotation.py", line 31, in <module>
    main()
  File "Awesome-Backbones\tools\get_annotation.py", line 10, in main
    classes, indexs = get_info(classes_path)
  File "Awesome-Backbones\utils\train_utils.py", line 128, in get_info
    name,index = data.split(' ')
ValueError: too many values to unpack (expected 2)

**Comment by Fafa-DL** [comment]
please check `Awesome-Backbones/datas/annotations.txt`, Make sure the format is as follows
```
class_name_1 index_1
class_name_2 index_2
class_name_3 index_3
```
E.g
```
daisy 0
dandelion 1
roses 2
sunflowers 3
tulips 4
```

**Comment by 1doshi** [comment]
my annotations.txt is correct

**Comment by Fafa-DL** [comment]
Maybe there are other spaces ` ` in your annotations.txt, my test here is normal

**Comment by 1doshi** [comment]
Ok, thanks for all :)
