### ISSUE TITLE
类别激活图可视化问题

### ISSUE THREAD

**Issue by Frostmournerr** [Fafa-DL/Awesome-Backbones#24]
请问类别激活图可视化中的EigenGradCAM方法是在哪篇论文中提出的呢，想了解一下原理

**Comment by Fafa-DL** [comment]
可以参考参考
[https://jacobgil.github.io/pytorch-gradcam-book/introduction.html](https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/eigen_grad_cam.py)
[https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/eigen_grad_cam.py](https://github.com/jacobgil/pytorch-grad-cam/blob/master/pytorch_grad_cam/eigen_grad_cam.py)
