### ISSUE TITLE
EfficientNetV2 is not working

### ISSUE THREAD

**Issue by BogdanovKirill** [Fafa-DL/Awesome-Backbones#25]
Hello!

First of all, I would like to thank you for great job! But it seems that EfficientNetV2 don't work. I tried this:
python tools/train.py models/efficientnetv2/efficientnetv2_xl_512.py
And received an error:
"AttributeError: 'EnhancedConvModule' object has no attribute 'in_channels'"
Could you fix it, please?

**Comment by Fafa-DL** [comment]
hi, thanks, the bug is fixed.
