### ISSUE TITLE
按照视频所给案例训练后log文件夹下无对应.pth文件

### ISSUE THREAD

**Issue by jaydapao** [Fafa-DL/Awesome-Backbones#26]
![1](https://user-images.githubusercontent.com/127706069/224594262-9708f8b7-ff21-472e-9228-56b613dfd8f9.png)
![2](https://user-images.githubusercontent.com/127706069/224594269-18b8e2be-e03d-43c3-b713-ec3e9fe90a42.png)
![3](https://user-images.githubusercontent.com/127706069/224594272-810112a8-83f0-43cb-a883-1779a5d18d60.png)
![4](https://user-images.githubusercontent.com/127706069/224594273-e5a67a1a-cb86-4d0a-b164-79fd37e6ba83.png)
![0](https://user-images.githubusercontent.com/127706069/224594284-29692db7-f1f9-4978-adfd-715afb5b4222.png)

**Comment by Fafa-DL** [comment]
hello，每个日期子文件下内容截图发下~

**Comment by Fafa-DL** [comment]
hello，每个日期子文件下内容截图发下~

**Comment by jaydapao** [comment]
![image](https://user-images.githubusercontent.com/127706069/224594958-65e23a9c-9d8a-4ce0-a377-c579f4853913.png)

**Comment by jaydapao** [comment]
![image](https://user-images.githubusercontent.com/127706069/224595004-209a31f0-b6dc-47a6-9f52-eae23101ac89.png)

**Comment by jaydapao** [comment]
![image](https://user-images.githubusercontent.com/127706069/224595023-335531a4-75c7-4588-a22c-098df4da40bc.png)

**Comment by jaydapao** [comment]
这个是今天训练的文件产出，但是训练到一般就终止了
![1](https://user-images.githubusercontent.com/127706069/224595092-3548ceea-562c-4840-85ed-5f3a196d1209.png)

**Comment by jaydapao** [comment]
13号的batch_size设置的是8还是16，那个线程数num_workers还是2没有改动

**Comment by Fafa-DL** [comment]
> ![image](https://user-images.githubusercontent.com/127706069/224595023-335531a4-75c7-4588-a22c-098df4da40bc.png)

这个不是有pth吗

**Comment by Fafa-DL** [comment]
有时候文件夹为空是因为你某一次训练没成功，但是默认在初始化的时候会创建文件夹

**Comment by Fafa-DL** [comment]
有时候文件夹为空是因为你某一次训练没成功，但是默认在初始化的时候会创建文件夹

**Comment by jaydapao** [comment]
> 

好的

**Comment by jaydapao** [comment]
> 这个是今天训练的文件产出，但是训练到一般就终止了 ![1](https://user-images.githubusercontent.com/127706069/224595092-3548ceea-562c-4840-85ed-5f3a196d1209.png)

那这个报错是什么，up能帮忙看看吗

**Comment by Fafa-DL** [comment]
memory不够了，降低batch（记得同步调学习率）

**Comment by jaydapao** [comment]
好的，感谢up主
