### ISSUE TITLE
数据集信息文件制作一步出现value error

### ISSUE THREAD

**Issue by jaydapao** [Fafa-DL/Awesome-Backbones#27]
![image](https://user-images.githubusercontent.com/127706069/225504524-65148c67-f1c6-4ed2-81f1-6135ae470270.png)
你好up，我是用自己的数据集制作的，请问这个报错如何解决

**Comment by Fafa-DL** [comment]
你的`annotations.txt`存在多余的空格，注意检查

**Comment by jaydapao** [comment]
![image](https://user-images.githubusercontent.com/127706069/225505412-d8ef57cf-a1a5-4a97-8d67-28b018b07755.png)
m应该是没有问题的

**Comment by Fafa-DL** [comment]
我一眼就看到6 7那里有问题

**Comment by jaydapao** [comment]
哦哦，是因为可能有多标签的原因吗

**Comment by jaydapao** [comment]
我知道了，谢谢up
