### ISSUE TITLE
第一轮top5为什么没有100%

### ISSUE THREAD

**Issue by rossxp** [Fafa-DL/Awesome-Backbones#3]
用的resnet34，除了文件夹位置没有修改任何代码，好奇怪的结果，其他epoch没问题。
![Uploading image.png…]()

**Comment by rossxp** [comment]
![image](https://user-images.githubusercontent.com/78269462/168047584-4818ef01-4b82-4348-87c2-be364ec033b1.png)

**Comment by Fafa-DL** [comment]
我这里刚刚测试的resnet34第一轮top5为100%没问题呀，类别数小于等于5一定是100
建议更新最新的repo，这段时间有一定改动，具体可以看更新记录
![image](https://user-images.githubusercontent.com/57349381/168067225-94bf37b6-ce7d-4a7d-8b92-0835318a110d.png)

**Comment by rossxp** [comment]
> 我这里刚刚测试的resnet34第一轮top5为100%没问题呀，类别数小于等于5一定是100 建议更新最新的repo，这段时间有一定改动，具体可以看更新记录 ![image](https://user-images.githubusercontent.com/57349381/168067225-94bf37b6-ce7d-4a7d-8b92-0835318a110d.png)

感谢回答
