### ISSUE TITLE
训练利用率问题

### ISSUE THREAD

**Issue by jaydapao** [Fafa-DL/Awesome-Backbones#33]
![image](https://user-images.githubusercontent.com/127706069/228821061-87740319-2993-4d64-ab0a-b91045a8fe76.png)
我导，这个训练利用率有问题吗，上一回跑swin transformer v2的时候没有出现偶尔是0的现象

**Comment by jaydapao** [comment]
![image](https://user-images.githubusercontent.com/127706069/228821429-0585a558-7899-4fc9-9e14-94842e25ce7f.png)

**Comment by Fafa-DL** [comment]
正常的~

**Comment by jaydapao** [comment]
好的，谢谢

**Comment by Fafa-DL** [comment]
你这个学习率和batchsize再调调，用了预训练模型不该这么低

**Comment by jaydapao** [comment]
好的，暂停训练是按什么键，可以暂停修改吗

**Comment by Fafa-DL** [comment]
肯定不可以暂停修改啊，配置文件在初始化的时候就读入了

**Comment by jaydapao** [comment]
好的，OK
