### ISSUE TITLE
请问怎样设置输入图像大一些，以提高准确率，原始图像是1280*960.

### ISSUE THREAD

**Issue by seaboat2009** [Fafa-DL/Awesome-Backbones#37]
请问，各个模型的输入图像是256*256，处理后变成224*224。如果我想让输入图像大一些，以提高准确率，该怎样设置？比如我的原始图像是1280*960的，请问我在哪里修改？谢谢！

**Comment by Fafa-DL** [comment]
模型input size是固定的，但可以尝试其他模式
