### ISSUE TITLE
请问ViT的base和large的区别是什么~

### ISSUE THREAD

**Issue by qjyyyy** [Fafa-DL/Awesome-Backbones#4]
另外Conformer、PoolFormer、TNT的训练配置文件是还没有更新嘛

up主好棒！！继续冲冲(｡ì _ í｡)

**Comment by Fafa-DL** [comment]
配置文件已更新

**Comment by qjyyyy** [comment]
好的收到！

btw，提一个小小的建议，输出的log文件夹中可以包含一下使用的参数配置文件(｡･ω･｡)ﾉ

**Comment by Fafa-DL** [comment]
谢谢建议，已更新参数配置文件的保存，此外还新增类别激活图可视化
