### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by IChun1G** [Fafa-DL/Awesome-Backbones#41]
Loading resnet18-f37072fd.pth
The model and loaded state dict do not match exactly

我在進行預訓練模型出錯，請問如何解決，謝謝

**Comment by Fafa-DL** [comment]
你是指分类层size不匹配吗？参考[#36 ](https://github.com/Fafa-DL/Awesome-Backbones/issues/36)
