### ISSUE TITLE
为什么训练之后的pth，在进行load时报错

### ISSUE THREAD

**Issue by wgc-hub** [Fafa-DL/Awesome-Backbones#42]
我下载的pth文件可以进行load，但是在训练之后为什么就不可以了，是因为模型结构发生了变化吗，那我应该怎么加载呢，比如当我想要进行部署的时候

**Comment by Fafa-DL** [comment]
你是训练的时候修改了网络结构还是什么？按正常流程训练完加载是没问题的，要么就是cfg相应位置没修改

**Comment by wgc-hub** [comment]
我通过torchvision加载了一个mobilenet_v3_small网络模型，进行torch.load可以正常加载
<img width="600" alt="截屏2023-05-06 14 04 22" src="https://user-images.githubusercontent.com/73543506/236604083-d9e84348-0f2b-4d5e-9e49-618a64964c42.png">
然后我把它训练一次之后得到的权重文件，在进行如上图一样的加载，就会报错，好像网络结构不一致了。
<img width="1162" alt="截屏2023-05-06 14 09 56" src="https://user-images.githubusercontent.com/73543506/236604582-611a3396-f404-4866-8dc0-7ae6b58e77ff.png">

**Comment by wgc-hub** [comment]
> 你是训练的时候修改了网络结构还是什么？按正常流程训练完加载是没问题的，要么就是cfg相应位置没修改

我通过torchvision加载了一个mobilenet_v3_small网络模型，进行torch.load可以正常加载
<img width="600" alt="截屏2023-05-06 14 04 22" src="https://user-images.githubusercontent.com/73543506/236604083-d9e84348-0f2b-4d5e-9e49-618a64964c42.png">
然后我把它训练一次之后得到的权重文件，在进行如上图一样的加载，就会报错，好像网络结构不一致了。
<img width="1162" alt="截屏2023-05-06 14 09 56" src="https://user-images.githubusercontent.com/73543506/236604582-611a3396-f404-4866-8dc0-7ae6b58e77ff.png">

**Comment by wgc-hub** [comment]
> 你是训练的时候修改了网络结构还是什么？按正常流程训练完加载是没问题的，要么就是cfg相应位置没修改

或者说我经过咱们这个系统训练完的pth文件，应该怎么在别的地方加载呢

**Comment by Fafa-DL** [comment]
torchvision对应的网络模型键名对不上当然权重无法映射，得在该项目下训才可以
