### ISSUE TITLE
我想把Top5修改成Top2的

### ISSUE THREAD

**Issue by zhoujinfeng1997** [Fafa-DL/Awesome-Backbones#43]
可以在你模型里修改吗，具体是怎么修改呢？在head上把topk=(1, 5)变为topk=(1,2)吗？这样也不对

**Comment by Fafa-DL** [comment]
hello，在cfg中将(1, 5)改成(1, 2)即可，因为终端输出的top5名称是被我写死的但实际数值还是和cfg中对应。你可以自己做个测试对比数值。
