### ISSUE TITLE
requirement安装依赖问题

### ISSUE THREAD

**Issue by jeenybride** [Fafa-DL/Awesome-Backbones#44]
![J9@$D81{S CDL4VEAZXYP27](https://github.com/Fafa-DL/Awesome-Backbones/assets/74750554/31c03146-b224-4aaa-8617-82123769bf27)
安装这两个安装不上
![EQ3637C2T{VXRJ )28V9C W](https://github.com/Fafa-DL/Awesome-Backbones/assets/74750554/dc437c5b-ed73-496b-80f9-99bb7ff137c5)
opencv_contrib_python
opencv-python-headless

**Comment by Fafa-DL** [comment]
单独下载这几个包，换源试试，如`pip install xxx -i https://pypi.tuna.tsinghua.edu.cn/simple`
