### ISSUE TITLE
如何将head中的分类问题转化为回归问题

### ISSUE THREAD

**Issue by mortonhan** [Fafa-DL/Awesome-Backbones#46]
感谢您提供的代码库，我目前的任务是关于含量多少的分类问题，如何通过修改head输出，使其能够成为解决回归问题的head，比如说我现在建立了三个梯度1,10,100分类模型，那我怎样预测5或者50的梯度，需要怎样在您的基础上修改

**Comment by Fafa-DL** [comment]
没太明白需求，“我目前的任务是关于含量多少的分类问题”，你这不是说了任务是分类吗？三个梯度是指什么意思

**Comment by mortonhan** [comment]
比如说我通过图像对猕猴桃的成熟度进行预测，我做实验只能选特定的几个成熟度去实验并收集数据（不可能将所有的成熟度的实验都做了，没有那么多的样品），比如我设定的实验成熟度设定为1,10, 100, 500，1000（每个浓度收集了大量的图像，这是分类问题），但是实际检测中遇到的肯定不止这五个浓度，如果遇到没有设定的浓度，例如3，不在我的实验图像中，也需要预测，这不就需要把分类问题转换为回归问题，因为需要把五个浓度连续起来，才能预测，这种问题需要怎样解决   (感谢回复！)

**Comment by Fafa-DL** [comment]
我的建议是可以以特定浓度作为训练，但最后基于该权重进行预测类别时，直接输出各类别置信度得分，自行对结果进行加权。
