### ISSUE TITLE
反馈一个潜在小Bug，在使用您的图像分类程序时，如果annoations填写顺序反向的话，在测试时可能会输出错误，如：high为2在第一行，low为0但在第三行，就会在单张图片测试时出现label和class对不上的bug

### ISSUE THREAD

**Issue by Psy-lzh** [Fafa-DL/Awesome-Backbones#49]
为了修改这个小bug，我修改了utils中的inference中部分语句以及单张图片测试的部分代码，目前已解决该bug

修改处为：
inference代码中新增label_names
def inference_model(model, image, val_pipeline, classes_names,label_names):

以及result['pred_class'] = classes_names[label_names.index(result['pred_label'])]

单张图片测试代码中修改了
classes_names, label_names = get_info(args.classes_map)

result = inference_model(model, args.img, val_pipeline, classes_names,label_names)

经测试修改后的代码已不会出现annoation顺序影响测试结果显示的小bug

**Comment by Fafa-DL** [comment]
hello，感谢反馈，可以提PR成为contributor，参考[如何给开源库提一个PR](https://zhuanlan.zhihu.com/p/346679852)，再次感谢~
