### ISSUE TITLE
我用自己的数据集，训练了100个epoch，但是训练输出的结果Precision, Recall, F1 Score三个参数为什么会出现大于1的现象，这不科学，没有找到是什么原因，求解答

### ISSUE THREAD

**Issue by mortonhan** [Fafa-DL/Awesome-Backbones#50]
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/15732843/d96af487-74d8-4aa8-bb57-6ae97125e05e)

**Comment by Fafa-DL** [comment]
训练什么模型出现的该情况？再跑一遍问题可否复现？尽量贴出终端信息方便溯源

**Comment by mortonhan** [comment]
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/15732843/7a10410d-2ff8-4a8b-8426-925418642fae)
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/15732843/fe6f9ab5-bcbb-4a54-94b9-9125c74d7849)
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/15732843/271f9508-b851-4f61-a8a4-23993638ac87)

训练的resnet50模型，我自己修改了一下bitchsize=32和学习率。其他的未做修改，第一遍跑了50epoch输出的csv中Precision, recall, F1 score均出现了大于1的现象，第二遍跑了 300 epoch中途也出现了大于1的现象，但是并没有报错

**Comment by Fafa-DL** [comment]
我用示例花卉数据集跑了多次，未出现这种情况，建议你跑跑其他如花卉等数据集看是否会出现该情况，先debug是code问题还是数据集问题；若未出现大于1情况，可以看看是否测试集哪里不对。影响准召率的只有GT与Pre
[```python](https://github.com/Fafa-DL/Awesome-Backbones/blob/b99083e8c5099604c95af0ccb9ea5cadfa7f7bd7/core/evaluations/eval_metrics.py#L96C1-L115)

**Comment by shiniaaaaa** [comment]
我训练VGG16也出现了Precision, recall, F1 score大于1的情况，不知道怎么回事
