### ISSUE TITLE
Mean Precision 、Mean Recall 、 Mean F1 Score指标很小是什么原因呢？

### ISSUE THREAD

**Issue by area6497** [Fafa-DL/Awesome-Backbones#55]
这是训练得到的结果：
+Validation Results-----+----------------+-------------+---------------+
| Top-1 Acc | Top-5 Acc | Mean Precision | Mean Recall | Mean F1 Score |
+-----------+-----------+----------------+-------------+---------------+
| 92.40     | 100.00    | 0.28           | 0.28        | 0.28          |

**Comment by Fafa-DL** [comment]
所提供的信息无法溯源啊。是用什么数据集什么模型跑的呢？
