### ISSUE TITLE
日志输出与保存的metrics_outpots.csv不一致，且Precision、Recall、F1 Score会＞1

### ISSUE THREAD

**Issue by shiniaaaaa** [Fafa-DL/Awesome-Backbones#56]
日志打印的Top-1、Top-5、Precision、Mean Recall、Mean F1 Score对不上，日志输出的Top1对应csv第三列数据，csv中没有top5的参数
![3f463d66d2e4d6c3ca3407da3841a8e](https://github.com/Fafa-DL/Awesome-Backbones/assets/102004207/9dcbc0b5-3698-4655-93ab-03062366ffa1)
![c68d8c1e06a1ba1d75379a97a03a3fc](https://github.com/Fafa-DL/Awesome-Backbones/assets/102004207/786768aa-3d57-4a0c-af31-db9f5f95a9a5)

**Comment by Fafa-DL** [comment]
hello, metrics_outputs依次保存的数据为'Train Loss', 'Top 1 Val Acc', 'Precision', 'Recall', 'F1 Score'详见[https://github.com/Fafa-DL/Awesome-Backbones/blob/main/utils/history.py#L27C1-L39](https://github.com/Fafa-DL/Awesome-Backbones/blob/main/utils/history.py#L27C1-L39)
大于1的问题建议检查下GT数据，[#50 ]也有相同情况

**Comment by shiniaaaaa** [comment]
> hello, metrics_outputs依次保存的数据为'Loss', 'Top 1 Val Acc', 'Precision', 'Recall', 'F1 Score'详见https://github.com/Fafa-DL/Awesome-Backbones/blob/main/utils/history.py#L27C1-L39 大于1的问题建议检查下GT数据，[#50 ]也有相同情况

感谢回复，想请问一下如何在训练结束后再去看某一轮的Top 5的值？是用tools/evaluation.py吗？我尝试多次后报错
![d77bd4c43cdbaa27014a9077963e40f](https://github.com/Fafa-DL/Awesome-Backbones/assets/102004207/a592fe71-ec88-4227-b148-a342160906d1)

**Comment by Fafa-DL** [comment]
top5的没有做同步报错诶，其实如果你阅读了源码，自己可以很轻松实现，我的接口都是松耦合

**Comment by jcdasheng** [comment]
>1是不是数据集的问题
