### ISSUE TITLE
swin transformer的分类训练结果为啥比官方源码低好多？是我哪里设置有误吗

### ISSUE THREAD

**Issue by 895318** [Fafa-DL/Awesome-Backbones#57]
up我用了该项目中的swin-b-224对我手上一个7分类的数据集进行训练，但是60多个epoch过去以后test-acc top1 只有70%+，同样的数据集差不多的迭代次数我用官方源码可以达到90%+，请问是我哪里设置的不合适吗？
我就改了以下内容其他没动：num_classes、batch_size、num_workers、pretrained_weights，
其中预训练模型是swin官网上在ImageNet22k上的swin_base_patch4_window7_224_22k.pth。
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/115165043/46035f03-d743-499a-900a-d42802cc835a)

**Comment by Fafa-DL** [comment]
按我经验来看学习率需要按你调的batch size同步修改，学习率影响很大

**Comment by 895318** [comment]
> 按我经验来看学习率需要按你调的batch size同步修改，学习率影响很大

那请问学习率和batch-size的关系一般是怎样的呢，我的数据集大概训练集8000+张，测试集2000+张。batch-size调低则相应的lr是应该是低一点还是高一点？请问up项目里的这个*32/64是什么意思？和你原始设置的batch-size=32是否有联系？我看swin 源码里的学习率是_C.TRAIN.BASE_LR = 5e-4（batch-size=32）
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/115165043/e73e42a6-17fe-4f2a-820e-612ee146e1c1)

**Comment by Fafa-DL** [comment]
batch-size调低则相应的lr是应该是低一点，配置文件中batch 32和公式中的32对应，你先同步替换更改学习率再测试准确率是否有提升

**Comment by 895318** [comment]
> batch-size调低则相应的lr是应该是低一点，配置文件中batch 32和公式中的32对应，你先同步替换更改学习率再测试准确率是否有提升

感觉变化不大...我甚至还换了台设备，在修改batch-size的同时也修改了学习率，无论是调整公式里的32还是直接把学习率调小，结果都很惨...不知道是什么原因（如图）....另外还有个问题想问up，项目里的模型可以从checkpoint恢复训练吗？好像在设置文件里没有看见这行
![581e5acf04b7bf9e719f236437d6d7d](https://github.com/Fafa-DL/Awesome-Backbones/assets/115165043/ea6a1e70-84ed-4e38-b82e-ead40404ac96)

**Comment by Fafa-DL** [comment]
我比较喜欢用1e-4你可以试试，调lr是个杂活。恢复训练是支持的，训练那块有教程你可以看看[https://github.com/Fafa-DL/Awesome-Backbones/blob/main/datas/docs/How_to_train.md](https://github.com/Fafa-DL/Awesome-Backbones/blob/main/datas/docs/How_to_train.md)

**Comment by 895318** [comment]
> 我比较喜欢用1e-4你可以试试，调lr是个杂活。恢复训练是支持的，训练那块有教程你可以看看https://github.com/Fafa-DL/Awesome-Backbones/blob/main/datas/docs/How_to_train.md

好的我再调调，请问up“是否每个Epoch更新学习率”这个设置true或false会在哪方面产生不同呢...
T^T多谢

**Comment by Fafa-DL** [comment]
我在B站视频中有讲你可以看看。还有一个很重要的和提升精度有关的操作是你可以选择性的关掉一些图像增强操作，经测试有时候那些增强反而污染数据

**Comment by jcdasheng** [comment]
你们recall都大于1吗
