### ISSUE TITLE
设置了seed，但是训练结果还是无法复现，

### ISSUE THREAD

**Issue by kyla2** [Fafa-DL/Awesome-Backbones#62]
设置了seed，但是训练结果还是无法复现，每次训练的结果具有随机性

**Comment by Fafa-DL** [comment]
建议把增强方式去掉

**Comment by kyla2** [comment]
> 建议把增强方式去掉

设置了 seed 后，增强不是也是每次一样吗，为什么会产生不一样的结果？

**Comment by Fafa-DL** [comment]
> > 建议把增强方式去掉
> 
> 设置了 seed 后，增强不是也是每次一样吗，为什么会产生不一样的结果？

比如randomcropsize这种，可以debug保存到本地，是否每次裁剪区域相同
