### ISSUE TITLE
数据集制作 

### ISSUE THREAD

**Issue by zhaozhengyang01** [Fafa-DL/Awesome-Backbones#63]
现在有train和test两个文件夹和train.csv文件。train.csv中有train文件夹中的图片和对应标签，我已经将train文件夹按照类别标签重新分类，test文件夹该怎么处理？test文件夹没有对应的test.csv文件，也就是没有类别标签，无法分类

**Comment by Fafa-DL** [comment]
项目中的验证集是有标签的，为了评估训练集训练精度。若此处你的验证集没有标签，可以拿训练集中的一小部分作为验证集
