### ISSUE TITLE
训练自己的数据集出现过拟合

### ISSUE THREAD

**Issue by kyla2** [Fafa-DL/Awesome-Backbones#64]
训练自己的数据集出现过拟合，请问下怎么调整比较合适？
![loss-acc](https://github.com/Fafa-DL/Awesome-Backbones/assets/38037081/200e9968-5df4-4027-964b-929e3995b281)

**Comment by Fafa-DL** [comment]
那这就是深度学习中常见问题了
- 增加训练数据量，如果数据量有限，可以考虑数据增强技术来生成更多的训练样本
- 选择合适的模型复杂度，过于复杂的模型容易过拟合，因此要选择适当的模型复杂度，避免模型过度拟合训练数据
- Early Stopping，监控模型在验证集上的精度，在性能不再提升时及时停止训练，防止模型在训练集上过拟合
- 使用交叉验证
- 调整超参数如学习率、批大小等

**Comment by wrqf** [comment]
@kyla2 请问怎么在图片中加入 Train acc的数据？
