### ISSUE TITLE
我在训练shufflenet_v2时，总是异常中断，请问是什么问题呢 

### ISSUE THREAD

**Issue by wangshiwei567** [Fafa-DL/Awesome-Backbones#7]
我在训练shufflenet_v2时，总是异常中断，请问是什么问题呢 
![2022-08-04 13-20-55屏幕截图](https://user-images.githubusercontent.com/97876428/182769092-de9d5426-891c-4d7b-82b9-e9321b6eb882.png)
![2022-08-04 13-20-44屏幕截图](https://user-images.githubusercontent.com/97876428/182769107-c7106d3d-f9de-4d0e-9537-922b2c97f6a8.png)

**Comment by Fafa-DL** [comment]
贴出报错信息

**Comment by Fafa-DL** [comment]
刚想来评论你就关闭了，这个考虑是matplotlib引起的报错，在utils/history下置顶部分插入
import matplotlib
matplotlib.use('Agg')
在最新版已经修复该问题，可以自行拉取或修改

**Comment by wangshiwei567** [comment]
我也查出来是这个问题了，已解决
