### ISSUE TITLE
批量图像检测结果的保存

### ISSUE THREAD

**Issue by PenneyNiu** [Fafa-DL/Awesome-Backbones#74]
你好！请问我已经完成了训练和批量图像检测，也成功保存了每一张检测后的图片，非常nice！但是我在B站评论区看到批量检测的预测结果信息也会保存csv文件，请问这个文件具体路径在哪，我找遍了也没有发现，请赐教谢谢！

**Comment by Fafa-DL** [comment]
只有evaluate会保存所有指标，tools下的batch test不会

**Comment by PenneyNiu** [comment]
> 只有evaluate会保存所有指标，tools下的batch test不会

好的，非常感谢！
