### ISSUE TITLE
加载权重文件失败

### ISSUE THREAD

**Issue by GaunX** [Fafa-DL/Awesome-Backbones#82]
Initialize the weights.
Loading resnet50_8xb32_in1k_20210831-ea4938fc.pth
The model and loaded state dict do not match exactly

size mismatch for head.fc.weight: copying a param with shape torch.Size([1000, 2048]) from checkpoint, the shape in current model is torch.Size([5, 2048]).
size mismatch for head.fc.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([5]).

**Comment by Fafa-DL** [comment]
这个是正常的，因为权重的分类头数量和你自己数据集分类头数量不一致
