### ISSUE TITLE
训练时数据数目与数据集的数目不匹配

### ISSUE THREAD

**Issue by leier0523** [Fafa-DL/Awesome-Backbones#83]
训练集数目应该是1500张+，但是在训练过程中epoch的数目变成了96，再重新训练又变成了48，请问是什么原因呀？

<img width="506" alt="3714c425006142ff4e8f6daacfe0abd" src="https://github.com/Fafa-DL/Awesome-Backbones/assets/150659092/867ebc40-c825-4e8d-9c4e-56e30bfb8df0">

**Comment by Fafa-DL** [comment]
检查配置文件中的batch size
