### ISSUE TITLE
数据集问题

### ISSUE THREAD

**Issue by xqc-qc** [Fafa-DL/Awesome-Backbones#85]
你好，这个模型库的mvit模型，可以训练视频数据吗？就是用你的代码对视频数据集能做出这样的格式吗？
![image](https://github.com/Fafa-DL/Awesome-Backbones/assets/128236906/fc919132-a9f8-46a6-be0b-f595e08c85fe)

**Comment by Fafa-DL** [comment]
视频数据不行啊
