### ISSUE TITLE
能否批量输出类激活图

### ISSUE THREAD

**Issue by tanyuhe** [Fafa-DL/Awesome-Backbones#86]
目前好像只能输出单张图像，而且指定保存路径出错，显示
Traceback (most recent call last):
  File "tools/vis_cam.py", line 357, in <module>
    main()
  File "tools/vis_cam.py", line 352, in main
    show_cam_grad(
  File "tools/vis_cam.py", line 255, in show_cam_grad
    cv2.imwrite(str(out_path), visualization_img)
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgcodecs\src\loadsave.cpp:696: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'cv::imwrite_'

**Comment by Fafa-DL** [comment]
这个我理解应该自己稍微加个循环就能实现

**Comment by tanyuhe** [comment]
OK，自己写了一个
import os

# 定义输入图片和模型文件的路径
input_dir = '测试文件夹'
model_path = '模型路径'

# 遍历目录及其子目录中的所有文件
for dirpath, dirnames, filenames in os.walk(input_dir):
    # 遍历当前目录下的文件
    for filename in filenames:
        # 检查文件是否为图片文件（这里假设图片文件以 .jpg 结尾）
        if filename.endswith('.jpg'):
            # 构建输入图片的完整路径
            input_image = os.path.join(dirpath, filename)

            # 调用 vis_cam.py 脚本并传递输入图片和模型路径作为参数
            os.system(f'python tools/vis_cam.py {input_image} {model_path} --save-path 输出路径'+filename)
