### ISSUE TITLE
作者您好，请教关于mobilenetv3 small的输出维度问题

### ISSUE THREAD

**Issue by Naturraalll** [Fafa-DL/Awesome-Backbones#89]
我使用您的代码，用flowers数据集，将num_classes设置为5，init_model（init_model是自带的）后会提示以下错误
size mismatch for head.layers.1.fc.weight: copying a param with shape torch.Size([1000, 1024]) from checkpoint, the shape in current model is torch.Size([5, 1024]).
size mismatch for head.layers.1.fc.bias: copying a param with shape torch.Size([1000]) from checkpoint, the shape in current model is torch.Size([5]).
问题：
1. 可以成功跑通，但我想将1000维度的输出修改为适合数据集的维度，请问该如何操作呢？
2. 请问不修改的话会带来什么不利影响呢？

**Comment by Fafa-DL** [comment]
这个没关系的，因为预训练模型的类别数是1000，所以分类头的size不匹配，你用到的更多是除分类头外的权重。
