### ISSUE TITLE
Transformer相关网络Loss=nan的问题

### ISSUE THREAD

**Issue by wwang487** [Fafa-DL/Awesome-Backbones#9]
最近在训练自己的数据集时，发现几个Transformer网络有时会出现loss=nan的情况，并且一旦出现这个情况，训练结果就不会发生任何的update.

想知道loss=nan会在怎样的情况下发生？谢谢

**Comment by Fafa-DL** [comment]
我现在随便试了个swin transformer网络，似乎一切正常，是不是你改动了学习率，建议先用默认设置跑通后再考虑调参

**Comment by Fafa-DL** [comment]
拉取刚刚的最新版本试试，修复了一个数据增强bug
