### ISSUE TITLE
怎么改变批量预测的结果字体的大小

### ISSUE THREAD

**Issue by pdqdw** [Fafa-DL/Awesome-Backbones#96]

**Comment by Fafa-DL** [comment]
1. 可将[https://github.com/Fafa-DL/Awesome-Backbones/blob/e97dd70694a98c64692a275bcec9ba381e80c3a4/utils/inference.py#L72](https://github.com/Fafa-DL/Awesome-Backbones/blob/e97dd70694a98c64692a275bcec9ba381e80c3a4/utils/inference.py#L72)从`0.5`改为更小值；
2. 可将[https://github.com/Fafa-DL/Awesome-Backbones/blob/e97dd70694a98c64692a275bcec9ba381e80c3a4/utils/inference.py#L106](https://github.com/Fafa-DL/Awesome-Backbones/blob/e97dd70694a98c64692a275bcec9ba381e80c3a4/utils/inference.py#L106)从50改为更小值。

**Comment by pdqdw** [comment]
单个测试的时候出现预测结果重叠的问题怎们办
![1712640410793](https://github.com/Fafa-DL/Awesome-Backbones/assets/166367842/09fcd3f4-02a4-4dcc-be7f-aa93b265a924)

**Comment by pdqdw** [comment]
改了参数后左上角预测结果的字体还是没变化
![1712641214216](https://github.com/Fafa-DL/Awesome-Backbones/assets/166367842/48e733e6-cca3-4e59-828d-297e7fac39bc)

**Comment by Fafa-DL** [comment]
> 改了参数后左上角预测结果的字体还是没变化 ![1712641214216](https://private-user-images.githubusercontent.com/166367842/320733304-48e733e6-cca3-4e59-828d-297e7fac39bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTMxNTcsIm5iZiI6MTcxMjY1Mjg1NywicGF0aCI6Ii8xNjYzNjc4NDIvMzIwNzMzMzA0LTQ4ZTczM2U2LWNjYTMtNGU1OS04MjhkLTI5N2U3ZmFjMzliYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwODU0MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTgwOTk4ZGM1OGQ0YTZlZmMwZDNiYzVmZmY3NjdjNmRmNDRhOWUzMThhYzg0ZTY5ZDBhNmY4NmUzYzU4NzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xaViixrLgIXCWjqKD9YHTNusEgaeCKtedcV2WvUiqBM)

你如果是要调大的话就将前述提及的相应地方调大就行，我理解错了以为你要调小

**Comment by pdqdw** [comment]
我font_scale分别调到了0.9，5和50，font_size=int(font_scale * 50)调成了font_size=int(font_scale * 500)，左上角的预测结果字体大小还是没有变化

**Comment by pdqdw** [comment]
测试单张图片的时候更改参数字体大小会变化，批量测试的时候更改参数大小不变

**Comment by Fafa-DL** [comment]
批量的在这[https://github.com/Fafa-DL/Awesome-Backbones/blob/e97dd70694a98c64692a275bcec9ba381e80c3a4/core/visualization/image.py#L304](https://github.com/Fafa-DL/Awesome-Backbones/blob/e97dd70694a98c64692a275bcec9ba381e80c3a4/core/visualization/image.py#L304)
